execute @s ^ ^0.3 ^0.6 titleraw @p[r=3] title { "rawtext": [{"text": "§aTIME: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }

execute @s[scores={raceid=1,racescore=0}] ~ ~ ~ tellraw @a { "rawtext": [{"text": "§8"}  , {"selector": "@a[tag=winner]"}, {"text": "§a finished "}, { "translate": "track.1" }, {"text": "§a with a time of: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }
execute @s[scores={raceid=1,racescore=1}] ~ ~ ~ tellraw @a { "rawtext": [{"text": "§n "}, {"selector": "@a[tag=winner]"}, {"text": "§a finished "}, { "translate": "track.1" }, {"text": "§a with a time of: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }
execute @s[scores={raceid=1,racescore=2}] ~ ~ ~ tellraw @a { "rawtext": [{"text": "§i "}, {"selector": "@a[tag=winner]"}, {"text": "§a finished "}, { "translate": "track.1" }, {"text": "§a with a time of: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }
execute @s[scores={raceid=1,racescore=3}] ~ ~ ~ tellraw @a { "rawtext": [{"text": "§6 "}, {"selector": "@a[tag=winner]"}, {"text": "§a finished "}, { "translate": "track.1" }, {"text": "§a with a time of: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }
execute @s[scores={raceid=1,racescore=4}] ~ ~ ~ tellraw @a { "rawtext": [{"text": "§b "}, {"selector": "@a[tag=winner]"}, {"text": "§a finished "}, { "translate": "track.1" }, {"text": "§a with a time of: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }

execute @s[scores={raceid=2,racescore=0}] ~ ~ ~ tellraw @a { "rawtext": [{"text": "§8"}  , {"selector": "@a[tag=winner]"}, {"text": "§a finished "}, { "translate": "track.2" }, {"text": "§a with a time of: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }
execute @s[scores={raceid=2,racescore=1}] ~ ~ ~ tellraw @a { "rawtext": [{"text": "§n "}, {"selector": "@a[tag=winner]"}, {"text": "§a finished "}, { "translate": "track.2" }, {"text": "§a with a time of: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }
execute @s[scores={raceid=2,racescore=2}] ~ ~ ~ tellraw @a { "rawtext": [{"text": "§i "}, {"selector": "@a[tag=winner]"}, {"text": "§a finished "}, { "translate": "track.2" }, {"text": "§a with a time of: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }
execute @s[scores={raceid=2,racescore=3}] ~ ~ ~ tellraw @a { "rawtext": [{"text": "§6 "}, {"selector": "@a[tag=winner]"}, {"text": "§a finished "}, { "translate": "track.2" }, {"text": "§a with a time of: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }
execute @s[scores={raceid=2,racescore=4}] ~ ~ ~ tellraw @a { "rawtext": [{"text": "§b "}, {"selector": "@a[tag=winner]"}, {"text": "§a finished "}, { "translate": "track.2" }, {"text": "§a with a time of: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }

execute @s[scores={raceid=3,racescore=0}] ~ ~ ~ tellraw @a { "rawtext": [{"text": "§8"}  , {"selector": "@a[tag=winner]"}, {"text": "§a finished "}, { "translate": "track.3" }, {"text": "§a with a time of: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }
execute @s[scores={raceid=3,racescore=1}] ~ ~ ~ tellraw @a { "rawtext": [{"text": "§n "}, {"selector": "@a[tag=winner]"}, {"text": "§a finished "}, { "translate": "track.3" }, {"text": "§a with a time of: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }
execute @s[scores={raceid=3,racescore=2}] ~ ~ ~ tellraw @a { "rawtext": [{"text": "§i "}, {"selector": "@a[tag=winner]"}, {"text": "§a finished "}, { "translate": "track.3" }, {"text": "§a with a time of: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }
execute @s[scores={raceid=3,racescore=3}] ~ ~ ~ tellraw @a { "rawtext": [{"text": "§6 "}, {"selector": "@a[tag=winner]"}, {"text": "§a finished "}, { "translate": "track.3" }, {"text": "§a with a time of: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }
execute @s[scores={raceid=3,racescore=4}] ~ ~ ~ tellraw @a { "rawtext": [{"text": "§b "}, {"selector": "@a[tag=winner]"}, {"text": "§a finished "}, { "translate": "track.3" }, {"text": "§a with a time of: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }

execute @s[scores={raceid=4,racescore=0}] ~ ~ ~ tellraw @a { "rawtext": [{"text": "§8"}  , {"selector": "@a[tag=winner]"}, {"text": "§a finished "}, { "translate": "track.4" }, {"text": "§a with a time of: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }
execute @s[scores={raceid=4,racescore=1}] ~ ~ ~ tellraw @a { "rawtext": [{"text": "§n "}, {"selector": "@a[tag=winner]"}, {"text": "§a finished "}, { "translate": "track.4" }, {"text": "§a with a time of: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }
execute @s[scores={raceid=4,racescore=2}] ~ ~ ~ tellraw @a { "rawtext": [{"text": "§i "}, {"selector": "@a[tag=winner]"}, {"text": "§a finished "}, { "translate": "track.4" }, {"text": "§a with a time of: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }
execute @s[scores={raceid=4,racescore=3}] ~ ~ ~ tellraw @a { "rawtext": [{"text": "§6 "}, {"selector": "@a[tag=winner]"}, {"text": "§a finished "}, { "translate": "track.4" }, {"text": "§a with a time of: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }
execute @s[scores={raceid=4,racescore=4}] ~ ~ ~ tellraw @a { "rawtext": [{"text": "§b "}, {"selector": "@a[tag=winner]"}, {"text": "§a finished "}, { "translate": "track.4" }, {"text": "§a with a time of: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }

execute @s[scores={raceid=5,racescore=0}] ~ ~ ~ tellraw @a { "rawtext": [{"text": "§8"}  , {"selector": "@a[tag=winner]"}, {"text": "§a finished "}, { "translate": "track.5" }, {"text": "§a with a time of: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }
execute @s[scores={raceid=5,racescore=1}] ~ ~ ~ tellraw @a { "rawtext": [{"text": "§n "}, {"selector": "@a[tag=winner]"}, {"text": "§a finished "}, { "translate": "track.5" }, {"text": "§a with a time of: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }
execute @s[scores={raceid=5,racescore=2}] ~ ~ ~ tellraw @a { "rawtext": [{"text": "§i "}, {"selector": "@a[tag=winner]"}, {"text": "§a finished "}, { "translate": "track.5" }, {"text": "§a with a time of: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }
execute @s[scores={raceid=5,racescore=3}] ~ ~ ~ tellraw @a { "rawtext": [{"text": "§6 "}, {"selector": "@a[tag=winner]"}, {"text": "§a finished "}, { "translate": "track.5" }, {"text": "§a with a time of: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }
execute @s[scores={raceid=5,racescore=4}] ~ ~ ~ tellraw @a { "rawtext": [{"text": "§b "}, {"selector": "@a[tag=winner]"}, {"text": "§a finished "}, { "translate": "track.5" }, {"text": "§a with a time of: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }

execute @s[scores={raceid=6,racescore=0}] ~ ~ ~ tellraw @a { "rawtext": [{"text": "§8"}  , {"selector": "@a[tag=winner]"}, {"text": "§a finished "}, { "translate": "track.6" }, {"text": "§a with a time of: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }
execute @s[scores={raceid=6,racescore=1}] ~ ~ ~ tellraw @a { "rawtext": [{"text": "§n "}, {"selector": "@a[tag=winner]"}, {"text": "§a finished "}, { "translate": "track.6" }, {"text": "§a with a time of: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }
execute @s[scores={raceid=6,racescore=2}] ~ ~ ~ tellraw @a { "rawtext": [{"text": "§i "}, {"selector": "@a[tag=winner]"}, {"text": "§a finished "}, { "translate": "track.6" }, {"text": "§a with a time of: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }
execute @s[scores={raceid=6,racescore=3}] ~ ~ ~ tellraw @a { "rawtext": [{"text": "§6 "}, {"selector": "@a[tag=winner]"}, {"text": "§a finished "}, { "translate": "track.6" }, {"text": "§a with a time of: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }
execute @s[scores={raceid=6,racescore=4}] ~ ~ ~ tellraw @a { "rawtext": [{"text": "§b "}, {"selector": "@a[tag=winner]"}, {"text": "§a finished "}, { "translate": "track.6" }, {"text": "§a with a time of: §c"}, { "score": {"name": "seconds", "objective": "math" } }, {"text": "."}, { "score": {"name": "tenths", "objective": "math" } }, { "score": {"name": "hundredths", "objective": "math" } }, { "text": "s" }] }